name: C/C++ CI

on:
  push:
    branches: [ release-3.0 ]
  pull_request:
    branches: [ release-3.0 ]
  workflow_dispatch:
    branches: [ release-3.0 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: sudo apt-get install -y libssh-dev libcmocka-dev lcov
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: generate coveralls info
      run: |
        lcov --directory . --capture --output-file coverage.info
        lcov -o coverage.info -r coverage.info '*/test/*' '*/picohttpparser/*' '*libreactor/libreactor*'
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.info
